name: CI

on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6 # or alternative dependency management
      - uses: php-actions/phpstan@v3
        with:
          path: src/
          php_version: 8.1

  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root
          POSTGRES_DB: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make ci-tests
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432